"""Save-before-next adaptive teacher review, bounded to six persisted questions.

Provider calls run outside transactions. Claims and revisions use DB compare-and-swap
as well as row locks, including on SQLite. GET never calls a provider. Literal answers
are saved before generation, and remain editable when a provider fails.
"""
from __future__ import annotations

import copy
import hashlib
import json
import re
import uuid
from dataclasses import asdict
from datetime import datetime, timedelta
from functools import wraps

from django.db import OperationalError, transaction
from django.db.models import F
from django.utils import timezone

from curriculum.models import CurriculumImportJob, CurriculumTeacherReview
from curriculum.source_interpreter import (
    AnnexReference, HistoryEntry, InterpretedField, SourceReference,
    derive_operational_queue, resolve,
)
from curriculum.teacher_review_provider import BLOCKING_PROVIDER_ERRORS, ReviewProviderError, get_review_provider
from curriculum.teacher_review_source import source_document_context
from curriculum.teacher_review_questions import question_policy, question_scope_error
from curriculum.teacher_review_quote_values import quote_matches_labelled_value
from curriculum.learning_purpose import (
    assess_learning_purpose, learning_purpose_scope, purpose_proposal_has_valid_shape,
)

PURPOSE_DRAFT_ID = "purpose-review"
MAX_QUESTIONS = 6
MAX_ANSWER = 12000
CLAIM_TIMEOUT = timedelta(minutes=10)


class ReviewError(Exception):
    def __init__(self, message, status=409):
        self.status = status
        super().__init__(message)


def _controlled_db_busy(function):
    @wraps(function)
    def wrapped(*args, **kwargs):
        try:
            return function(*args, **kwargs)
        except OperationalError as exc:
            if "locked" in str(exc).lower() or "busy" in str(exc).lower():
                raise ReviewError("La revisión está ocupada en otra ventana. El borrador se conserva; vuelve a guardar cuando termine.", 503) from None
            raise
    return wrapped


def _unknown_answer(text):
    # Conservative whole-answer gate, not a list of complete phrases that a
    # model can evade by selecting a shorter quote. Negation/uncertainty stays
    # literal in history and unresolved; no fragment becomes a supported fact.
    return bool(re.search(
        r"\b(?:no|nunca|desconozco|ignoro|quiz[aá]s?|tal\s+vez|probablemente|"
        r"posiblemente|creo\s+que|supongo|dud[ao]|unknown|uncertain|maybe)\b",
        str(text), flags=re.IGNORECASE))


def _answer_target_eligible(turn, target, context):
    if (turn.get("answer_source_sha256") != context["dossier"]["source_sha256"]
            or type(turn.get("answer_dossier_version")) is not int
            or _unknown_answer(turn.get("answer", ""))):
        return False
    # Versions generated by this conversation are not independent decisions.
    own_versions = {u.get("dossier_version") for t in context["turns"] for u in t.get("applied", [])}
    item = next((t for t in context["all_targets"] if t["target_id"] == target), None)
    if item is None:
        return False
    for entry in context["dossier"].get("history", []):
        version = entry.get("version", 0)
        if entry.get("action") != "resolve" or version <= turn["answer_dossier_version"] or version in own_versions:
            continue
        for delta in entry.get("deltas", []):
            if (delta.get("scope") == item["scope"]
                    and delta.get("field") == (item["reference_id"] if item["scope"] == "annex" else item["field_name"])
                    and (item["scope"] == "general" or delta.get("session_id") == item["session_id"])):
                return False
    return True


def _ready(job):
    if not job.has_valid_ready_dossier() or job.interpretation_claim_token:
        raise ReviewError("La fuente cambió o requiere comprobación. Reextrae la planeación antes de continuar.")
    return job.get_interpretation_dossier()


def targets(dossier):
    return {item.target_id: item for item in derive_operational_queue(dossier).items}


def unresolved(dossier):
    return [asdict(item) for item in targets(dossier).values()
            if item.operational_state != "resolved"]


def _initial_state():
    return {"turns": [], "receipts": [], "status": "new", "error": "", "events": []}


def local_drafts(review):
    """Read per-turn drafts, including the original single-draft storage shape."""
    state = review.draft_state or {}
    if "drafts" in state:
        return copy.deepcopy(state["drafts"])
    if state.get("turn_id"):
        return {state["turn_id"]: copy.deepcopy(state)}
    return {}


@_controlled_db_busy
def open_review(job):
    dossier = _ready(job)
    review, _ = CurriculumTeacherReview.objects.get_or_create(
        job=job, defaults={"dossier_version": dossier.version,
                           "source_sha256": dossier.source_sha256, "state": _initial_state()})
    return review


def _check(review, dossier, expected_revision, expected_version):
    if review.source_sha256 != dossier.source_sha256 or review.dossier_version != dossier.version:
        raise ReviewError("La planeación cambió fuera de esta revisión. Tus respuestas siguen guardadas; recarga para comprobar el estado.")
    if review.revision != expected_revision or dossier.version != expected_version:
        raise ReviewError("Hay una versión más reciente. Tu texto no se ha sobrescrito; recarga antes de guardar de nuevo.")
    if review.generation_token:
        raise ReviewError("La siguiente pregunta aún está en preparación. Tu respuesta ya está guardada.")


def _cas(review, state, *, token=None, started=None, dossier_version=None,
         clear_draft_turn=None, expected_draft_epoch=None):
    draft_updates = {}
    match = {"pk": review.pk, "revision": review.revision}
    if clear_draft_turn:
        drafts = local_drafts(review)
        drafts.pop(clear_draft_turn, None)
        draft_updates = {"draft_state": {"drafts": drafts} if drafts else {},
                         "draft_epoch": F("draft_epoch") + 1}
        match["draft_epoch"] = expected_draft_epoch
    count = CurriculumTeacherReview.objects.filter(**match).update(
        state=state, revision=review.revision + 1, generation_token=token,
        generation_started_at=started, dossier_version=dossier_version or review.dossier_version,
        updated_at=timezone.now(), **draft_updates)
    if count != 1:
        raise ReviewError("La revisión cambió en otra ventana. Recarga para continuar.")
    review.refresh_from_db()


def _same_snapshot(current, previous):
    # Display/operational strings are derived on deserialization; compare only
    # durable domain data when checking whether our own application is current.
    derived = {"operational_state", "current_action", "action_required"}
    return ({k: v for k, v in current.items() if k not in derived}
            == {k: v for k, v in previous.items() if k not in derived})


def _save_dossier(job, dossier):
    state = job.save_interpretation_dossier(dossier)
    if state != CurriculumImportJob.INTERPRETATION_STATE_READY:
        raise ReviewError("La comprobación de la fuente bloqueó la corrección. Tu respuesta permanece en el historial.")


def _bump_answer(job, dossier, user, action, deltas=None):
    dossier.version += 1
    dossier.updated_at = timezone.now().isoformat()
    dossier.history.append(HistoryEntry(
        version=dossier.version, action=action, actor=user.username,
        timestamp=dossier.updated_at,
        summary="Respuesta literal docente guardada; no constituye aprobación.",
        deltas=deltas or [],
    ).to_dict())
    _save_dossier(job, dossier)


@_controlled_db_busy
def submit_answer(*, job_id, user, expected_revision, expected_version, expected_draft_epoch, receipt,
                  turn_id, answer, edit=False, skip=False):
    if not isinstance(answer, str) or len(answer) > MAX_ANSWER or (not skip and not answer.strip()):
        raise ReviewError("Escribe una respuesta de hasta 12 000 caracteres, o indica que no tienes ese dato.", 400)
    try:
        receipt = str(uuid.UUID(receipt))
    except (ValueError, TypeError, AttributeError):
        raise ReviewError("Identificador de envío inválido.", 400) from None
    fingerprint = hashlib.sha256(json.dumps([turn_id, answer, edit, skip], ensure_ascii=False).encode()).hexdigest()
    with transaction.atomic():
        job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
        dossier = _ready(job)
        review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
        state = copy.deepcopy(review.state)
        prior = next((r for r in state["receipts"] if r["id"] == receipt), None)
        if prior:
            if prior["fingerprint"] != fingerprint:
                raise ReviewError("Este envío ya fue usado con otro texto.")
            return review, False
        _check(review, dossier, expected_revision, expected_version)
        if type(expected_draft_epoch) is not int or expected_draft_epoch < 0:
            raise ReviewError("Versión del borrador inválida.", 400)
        if review.draft_epoch != expected_draft_epoch:
            raise ReviewError("Hay un borrador más reciente en otra ventana. Se conserva sin cambios; revisa antes de volver a guardar.")
        turn = next((t for t in state["turns"] if t["id"] == turn_id), None)
        if not turn or (not edit and turn["answer"] is not None) or (edit and turn["answer"] is None):
            raise ReviewError("La pregunta ya cambió. Recarga antes de contestar.")
        edit_deltas = []
        if edit:
            # Restore only this turn's own applied values when still current. A later
            # human answer or independent correction is never overwritten.
            available = targets(dossier)
            for update in reversed(turn.get("applied", [])):
                item = available.get(update["target_id"])
                if item and item.scope in ("general", "session"):
                    fields = (dossier.general_fields if item.scope == "general"
                              else dossier.get_session(item.session_id).fields)
                    current = fields.get(item.field_name)
                    if current and _same_snapshot(current.to_dict(), update["after"]):
                        if update["before"] is None:
                            fields.pop(item.field_name)
                        else:
                            fields[item.field_name] = InterpretedField.from_dict(update["before"])
                        edit_deltas.append({"scope": item.scope, "field": item.field_name,
                            "session_id": item.session_id,
                            "change_type": "removed" if update["before"] is None else "modified",
                            "before": update["after"], "after": update["before"]})
                elif item and item.scope == "annex":
                    refs = dossier.get_session(item.session_id).annex_references
                    for index, ref in enumerate(refs):
                        if ref.reference_id == item.reference_id and _same_snapshot(ref.to_dict(), update["after"]):
                            refs[index] = AnnexReference.from_dict(update["before"])
                            edit_deltas.append({"scope": "annex", "field": item.reference_id,
                                "session_id": item.session_id, "change_type": "modified",
                                "before": update["after"], "after": update["before"]})
            turn["applied"] = []
        turn["answer_history"].append({"answer": answer, "skipped": skip,
                                      "at": timezone.now().isoformat(), "actor": user.username,
                                      "source_sha256": dossier.source_sha256})
        turn["answer"] = answer  # exact submitted text, including whitespace
        turn["skipped"] = skip
        turn["pending_processing"] = True
        state["receipts"].append({"id": receipt, "fingerprint": fingerprint})
        state["receipts"] = state["receipts"][-64:]
        state.update(status="pending", error=state.get("error", "") if state.get("error") in BLOCKING_PROVIDER_ERRORS else "")
        _bump_answer(job, dossier, user, "teacher_review_answer_edit" if edit else "teacher_review_answer", edit_deltas)
        turn["answer_source_sha256"] = dossier.source_sha256
        turn["answer_dossier_version"] = dossier.version
        _cas(review, state, dossier_version=dossier.version, clear_draft_turn=turn_id,
             expected_draft_epoch=expected_draft_epoch)
        return review, True



def needs_manual_recovery(review, dossier):
    """Silent model output cannot close unresolved required data. GET is read-only."""
    return bool(dossier and review.state.get('status') in ('needs_input', 'limited', 'complete')
                and not any(turn['answer'] is None for turn in review.state.get('turns', []))
                and any(item.priority_state == 'requires_resolution' for item in targets(dossier).values()))


def purpose_review_available(review, dossier):
    """Allow explicit review, including an empty purpose after rejected output."""
    if dossier is None or review.source_sha256 != dossier.source_sha256:
        return False
    current = dossier.general_fields.get('proposito')
    assessments = [item for item in review.state.get('purpose_assessments', [])
                   if item.get('source_sha256') == dossier.source_sha256]
    human_reviews = any(item.get('source_sha256') == dossier.source_sha256
                        for item in review.state.get('purpose_reviews', []))
    if current is None or not current.value:
        return bool(needs_manual_recovery(review, dossier)
                    or any(item.get('decision') == 'abstained' for item in assessments))
    return bool(current.origin in ('proposed', 'teacher_entered') and (human_reviews
                or any(item.get('decision') == 'proposed' for item in assessments)))


@_controlled_db_busy
def request_another_question(*, job_id, user, expected_revision, expected_version):
    """Only an explicit request can leave manual recovery for a new model call."""
    with transaction.atomic():
        job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
        dossier = _ready(job)
        review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
        _check(review, dossier, expected_revision, expected_version)
        state = copy.deepcopy(review.state)
        if state.get('error') in BLOCKING_PROVIDER_ERRORS:
            raise ReviewError('La consulta anterior requiere revisión o conciliación antes de solicitar otra. Su registro se conserva.')
        if len(state['turns']) >= MAX_QUESTIONS:
            raise ReviewError('Ya se alcanzó el máximo de seis preguntas. Revisa los datos pendientes y los campos disponibles manualmente.')
        if not needs_manual_recovery(review, dossier):
            raise ReviewError('No hay una aclaración pendiente disponible para otra pregunta.')
        state['status'] = 'pending'
        state['events'].append({'kind': 'explicit_question_request', 'at': timezone.now().isoformat(),
            'actor': user.username, 'source_sha256': dossier.source_sha256,
            'dossier_version': dossier.version, 'questions_remaining': MAX_QUESTIONS - len(state['turns'])})
        _cas(review, state)
        return review


@_controlled_db_busy
def review_learning_purpose(*, job_id, user, expected_revision, expected_version,
                            expected_draft_epoch, receipt, answer, confirmed):
    """Explicit human field review, never a question, model call or approval."""
    if confirmed is not True:
        raise ReviewError('Confirma que revisaste el propósito antes de guardarlo.', 400)
    if not isinstance(answer, str) or not answer.strip() or len(answer) > MAX_ANSWER:
        raise ReviewError('Escribe el propósito revisado, hasta 12 000 caracteres.', 400)
    try:
        receipt = str(uuid.UUID(receipt))
    except (ValueError, TypeError, AttributeError):
        raise ReviewError('Identificador de envío inválido.', 400) from None
    fingerprint = hashlib.sha256(json.dumps(['purpose_review', answer], ensure_ascii=False).encode()).hexdigest()
    with transaction.atomic():
        job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
        dossier = _ready(job)
        review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
        state = copy.deepcopy(review.state)
        prior = next((item for item in state['receipts'] if item['id'] == receipt), None)
        if prior:
            if prior['fingerprint'] != fingerprint:
                raise ReviewError('Este envío ya fue usado con otro texto.')
            return review
        _check(review, dossier, expected_revision, expected_version)
        if type(expected_draft_epoch) is not int or expected_draft_epoch != review.draft_epoch:
            raise ReviewError('Hay un borrador más reciente. Se conserva sin cambios; recarga antes de guardar.')
        if not purpose_review_available(review, dossier):
            raise ReviewError('No hay una propuesta de propósito revisable para esta fuente.')
        before_version = dossier.version
        dossier = resolve(dossier, {'general_fields': {'proposito': answer}},
                          actor=user.username, pdf_source=job.pdf)
        if dossier.version == before_version:
            dossier = resolve(dossier, {'reviews': {'proposito': 'confirmed'}},
                              actor=user.username, pdf_source=job.pdf)
        if dossier.version != before_version:
            _save_dossier(job, dossier)
        state.setdefault('purpose_reviews', []).append({'answer': answer,
            'source_sha256': dossier.source_sha256, 'dossier_version': dossier.version,
            'actor': user.username, 'at': timezone.now().isoformat()})
        state['receipts'].append({'id': receipt, 'fingerprint': fingerprint})
        state['receipts'] = state['receipts'][-64:]
        state['events'].append({'kind': 'human_purpose_review', 'at': timezone.now().isoformat(),
                                'dossier_version': dossier.version, 'question_count': len(state['turns'])})
        if state.get('status') in ('needs_input', 'limited', 'complete'):
            state['status'] = ('asking' if any(turn['answer'] is None for turn in state['turns'])
                else 'needs_input' if any(item.priority_state == 'requires_resolution'
                                          for item in targets(dossier).values())
                else 'limited' if unresolved(dossier) else 'complete')
        _cas(review, state, dossier_version=dossier.version,
             clear_draft_turn=PURPOSE_DRAFT_ID, expected_draft_epoch=expected_draft_epoch)
        return review

def _context(job, dossier, state):
    turns = copy.deepcopy(state["turns"])
    # Provider receives all original sessions/activities/annexes/provenance, not a
    # first-session projection. Provider output can only modify explicit targets.
    context = {"dossier": copy.deepcopy(job.interpretation_dossier), "turns": turns,
            "missing_fields": unresolved(dossier),
            "questions_asked": len(turns), "max_questions": MAX_QUESTIONS,
            "questions_remaining": 0 if any(t["answer"] is None for t in turns) else MAX_QUESTIONS - len(turns),
            "all_targets": [asdict(t) for t in targets(dossier).values()]}
    context["question_policy"] = question_policy(context["all_targets"])
    for turn in turns:
        turn["eligible_targets"] = [target for target in turn["targets"] if _answer_target_eligible(turn, target, context)] if turn["answer"] is not None else []
    if not context["question_policy"]["candidate_target_ids"]:
        context["questions_remaining"] = 0
    return context


def _answer_processing_pending(turn, state):
    if "pending_processing" in turn:
        return turn["pending_processing"] is True
    # Pre-flag rows already record server timestamps for each literal answer
    # and successful provider application. Only an answer newer than the last
    # accepted result is pending; a resume must not replay old processed facts.
    if state["status"] != "pending" or not turn.get("answer_history"):
        return False
    try:
        answered_at = datetime.fromisoformat(turn["answer_history"][-1]["at"])
        processed_at = [datetime.fromisoformat(event["at"]) for event in state["events"]
                        if event.get("kind") == "provider_result"]
        if answered_at.tzinfo is None or any(at.tzinfo is None for at in processed_at):
            return False
        return not processed_at or answered_at > max(processed_at)
    except (KeyError, TypeError, ValueError):
        return False


def _validate_output(output, context):
    if (not isinstance(output, dict) or not {"question", "targets", "answer_updates"}.issubset(output)
            or set(output) - {"question", "targets", "answer_updates", "purpose_proposal"}):
        raise ReviewProviderError("invalid_output")
    if output.get("purpose_proposal") is not None and not purpose_proposal_has_valid_shape(output["purpose_proposal"]):
        raise ReviewProviderError("invalid_purpose_proposal")
    question, asked, updates = output["question"], output["targets"], output["answer_updates"]
    allowed = {t["target_id"] for t in context["all_targets"]}
    if not isinstance(asked, list) or not all(isinstance(t, str) and t in allowed for t in asked) or len(asked) != len(set(asked)):
        raise ReviewProviderError("invalid_targets")
    if question is not None and (not isinstance(question, str) or not question.strip() or len(question) > 2000 or not asked):
        raise ReviewProviderError("invalid_question")
    if question is not None and any(t not in {i["target_id"] for i in context["missing_fields"]} for t in asked):
        raise ReviewProviderError("question_has_no_missing_target")
    if question is None and asked:
        raise ReviewProviderError("invalid_completion")
    if context["questions_remaining"] == 0 and question is not None:
        raise ReviewProviderError("question_limit")
    scope_error = question_scope_error(question, asked, context.get("question_policy"))
    if scope_error:
        raise ReviewProviderError(scope_error)
    if not isinstance(updates, list) or len(updates) > 200:
        raise ReviewProviderError("invalid_updates")
    turns = {t["id"]: t for t in context["turns"]}
    seen = set()
    latest_by_target = {}
    for turn in turns.values():
        if turn["answer"] is not None and not turn.get("skipped"):
            for target in turn["targets"]:
                prior = latest_by_target.get(target)
                if prior is None or turn["answer_history"][-1]["at"] > prior["answer_history"][-1]["at"]:
                    latest_by_target[target] = turn
    for update in updates:
        if not isinstance(update, dict) or set(update) != {"turn_id", "target_id", "quote"}:
            raise ReviewProviderError("invalid_update")
        turn = turns.get(update["turn_id"])
        quote = update["quote"]
        if (not turn or turn["answer"] is None or turn.get("skipped")
                or update["target_id"] not in turn["targets"] or update["target_id"] not in allowed
                or not isinstance(quote, str) or not quote.strip() or quote not in turn["answer"]
                or update["target_id"] in seen
                or latest_by_target.get(update["target_id"], {}).get("id") != turn["id"]
                or _unknown_answer(quote)
                or not _answer_target_eligible(turn, update["target_id"], context)):
            raise ReviewProviderError("unsupported_human_value")
        if not quote_matches_labelled_value(quote, update["target_id"], turn, context["all_targets"]):
            raise ReviewProviderError("human_quote_includes_metadata_or_wrong_field")
        seen.add(update["target_id"])
    return output


def _apply_updates(job, dossier, state, output, user):
    available = targets(dossier)
    for update in output["answer_updates"]:
        item = available[update["target_id"]]
        turn = next(t for t in state["turns"] if t["id"] == update["turn_id"])
        quote = update["quote"]
        # Idempotent retry of processing the same literal answer.
        if any(u["target_id"] == item.target_id and u["quote"] == quote for u in turn.get("applied", [])):
            continue
        if item.scope in ("general", "session"):
            fields = dossier.general_fields if item.scope == "general" else dossier.get_session(item.session_id).fields
            before = fields[item.field_name].to_dict() if item.field_name in fields else None
            payload = ({"general_fields": {item.field_name: quote}} if item.scope == "general"
                       else {"session_id": item.session_id, "session_fields": {item.field_name: quote}})
            dossier = resolve(dossier, payload, actor=user.username, pdf_source=job.pdf)
            fields = dossier.general_fields if item.scope == "general" else dossier.get_session(item.session_id).fields
            after = fields[item.field_name].to_dict()
            # resolve deliberately treats unchanged data as a no-op. Keep it as PDF
            # evidence when unchanged; never pretend a model approved it.
        elif item.scope == "annex":
            if not quote.isascii() or not quote.isdecimal() or quote.startswith("0"):
                raise ReviewProviderError("invalid_annex_page")
            page = int(quote)
            if not 1 <= page <= dossier.page_count:
                raise ReviewProviderError("invalid_annex_page")
            ref = next(r for r in dossier.get_session(item.session_id).annex_references
                       if r.reference_id == item.reference_id)
            before = ref.to_dict()
            dossier = resolve(dossier, {"session_id": item.session_id,
                "annex_confirmations": {item.reference_id: page},
                "manual_annex_confirmations": {item.reference_id: {"page": page, "confirmed": True}}},
                actor=user.username, pdf_source=job.pdf)
            after = ref.to_dict()
        else:
            raise ReviewProviderError("unsupported_target")
        turn.setdefault("applied", []).append({**update, "before": before, "after": after,
                                                   "dossier_version": dossier.version})
    return dossier



def _purpose_policy(context):
    current = context['dossier']['general_fields'].get('proposito', {})
    eligible = (not current.get('value') and current.get('origin') != 'teacher_entered'
                and current.get('review') not in ('confirmed', 'corrected'))
    scope = learning_purpose_scope(context['source_document']) if eligible else None
    target = next((item['target_id'] for item in context['all_targets']
                   if item['scope'] == 'general' and item['field_name'] == 'proposito'), None)
    public_scope = ({key: scope[key] for key in ('scope_id', 'project_heading', 'project_page', 'membership')}
                    if scope else None)
    return {'eligible': bool(eligible and scope and target), 'target_id': target,
            'source_scope': public_scope, 'review_required': True}


def _apply_purpose_candidate(dossier, state, output, context):
    candidate = output.get('purpose_proposal')
    if candidate is None:
        return False
    current = dossier.general_fields.get('proposito')
    # Recheck AFTER human updates and against the locked current dossier. An
    # explicit correction, including an empty human field, outranks inference.
    if (current and (current.value or current.origin == 'teacher_entered'
                     or current.review in ('confirmed', 'corrected'))):
        assessment = {'decision': 'abstained', 'issues': ['current_purpose_retained'],
                      'review': 'pending', 'value': None}
    else:
        assessment = assess_learning_purpose(candidate, context['source_document'])
    assessment = {**assessment, 'source_sha256': dossier.source_sha256,
                  'dossier_version': dossier.version, 'at': timezone.now().isoformat()}
    state.setdefault('purpose_assessments', []).append(assessment)
    if assessment['decision'] != 'proposed':
        return False
    before = current.to_dict() if current else None
    proposed = InterpretedField(name='proposito', value=assessment['value'],
        origin='proposed', status='ambiguous', review='pending', reason=assessment['reason'],
        evidence=[SourceReference.from_dict(item) for item in assessment['evidence']])
    dossier.general_fields['proposito'] = proposed
    dossier.version += 1
    dossier.updated_at = timezone.now().isoformat()
    dossier.history.append(HistoryEntry(version=dossier.version, action='teacher_review_purpose_proposal',
        actor='Asistente (propuesta)', timestamp=dossier.updated_at,
        summary='Propósito inferido con evidencia; requiere revisión docente y no constituye aprobación.',
        deltas=[{'scope': 'general', 'field': 'proposito', 'change_type': 'modified',
                 'before': before, 'after': proposed.to_dict()}]).to_dict())
    assessment['dossier_version'] = dossier.version
    return True

@_controlled_db_busy
def advance_review(*, job_id, user, expected_revision, expected_version, provider=None):
    """One claimed request, one provider response; failures never roll back answers."""
    with transaction.atomic():
        job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
        dossier = _ready(job)
        review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
        _check(review, dossier, expected_revision, expected_version)
        state = copy.deepcopy(review.state)
        if state.get("error") in BLOCKING_PROVIDER_ERRORS:
            if state["error"] in ("luna_response_rejected", "pi_response_rejected", "human_quote_includes_metadata_or_wrong_field"):
                raise ReviewError("La respuesta anterior se rechazó y su recibo se conserva. No se enviará otra sin revisar el rechazo y obtener una autorización nueva.")
            raise ReviewError("La consulta anterior tiene estado y consumo pendientes de conciliación. No se enviará otra sin una autorización nueva.")
        if state["status"] in ("complete", "limited", "needs_input"):
            return review
        # An unanswered persisted question is resumed, never regenerated by a reload/retry.
        if state["status"] == "asking":
            return review
        context = _context(job, dossier, state)
        pending_answer = any(_answer_processing_pending(t, state) and not t.get("skipped")
                             and t["eligible_targets"] for t in context["turns"])
        if not context["question_policy"]["candidate_target_ids"] and not pending_answer:
            unanswered = any(turn["answer"] is None for turn in state["turns"])
            state.update(status="asking" if unanswered else
                         "limited" if context["missing_fields"] else "complete", error="")
            for turn in state["turns"]:
                turn["pending_processing"] = False
            _cas(review, state)
            return review
        token = uuid.uuid4()
        _cas(review, state, token=token, started=timezone.now())
        claimed_revision = review.revision
    provider_receipt = None
    failure_code = "provider_unavailable"
    try:
        # Parsing happens after the claim transaction commits. It reads one
        # SHA-verified byte snapshot and includes every physical page, rather
        # than assuming the interpreted dossier contains all literal PDF text.
        context["source_document"] = source_document_context(job, dossier)
        context["purpose_policy"] = _purpose_policy(context)
        provider_output = (provider or get_review_provider())(context)
        # Keep transport accounting independently of every later application,
        # source, transaction or ownership check. Rejection is not zero usage.
        provider_receipt = getattr(provider_output, "provider_receipt", None)
        output = _validate_output(provider_output, context)
        with transaction.atomic():
            job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
            review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
            if review.generation_token != token or review.revision != claimed_revision:
                failure_code = "stale_provider_result"
                raise ReviewError("La respuesta del asistente quedó obsoleta; recarga la revisión.")
            failure_code = "source_changed_during_request"
            dossier = _ready(job)
            if dossier.version != context["dossier"]["version"] or dossier.source_sha256 != review.source_sha256:
                failure_code = "dossier_changed_during_request"
                raise ReviewError("La planeación cambió durante la consulta. Tus respuestas siguen guardadas.")
            failure_code = "provider_unavailable"
            state = copy.deepcopy(review.state)
            dossier = _apply_updates(job, dossier, state, output, user)
            proposed_purpose = _apply_purpose_candidate(dossier, state, output, context)
            # A valid human quote may have just resolved the last true gap.
            # Evaluate question scope again against that resulting dossier;
            # source confirmations and optional blanks never become new gaps.
            scope_error = question_scope_error(output["question"], output["targets"],
                question_policy([asdict(item) for item in targets(dossier).values()]))
            if scope_error:
                raise ReviewProviderError(scope_error)
            if output["answer_updates"] or proposed_purpose:
                _save_dossier(job, dossier)
            question = output["question"]
            unanswered = next((t for t in state["turns"] if t["answer"] is None), None)
            if question is not None:
                if unanswered:
                    # A corrected answer does not authorize an uncounted replacement
                    # question. Persisted questions are resumed with their exact text.
                    raise ReviewProviderError("unanswered_question_exists")
                elif len(state["turns"]) < MAX_QUESTIONS:
                    state["turns"].append({"id": str(uuid.uuid4()), "question": question,
                        "targets": output["targets"], "answer": None, "skipped": False,
                        "answer_history": [], "applied": [], "question_source_sha256": dossier.source_sha256})
                else:
                    raise ReviewProviderError("question_limit")
                state["status"] = "asking"
            else:
                state["status"] = ("asking" if unanswered
                                   else "needs_input" if any(item.priority_state == "requires_resolution"
                                                            for item in targets(dossier).values())
                                   else "limited" if unresolved(dossier) else "complete")
            state["error"] = ""
            for turn in state["turns"]:
                turn["pending_processing"] = False
            event = {"at": timezone.now().isoformat(), "kind": "provider_result",
                     "question_count": len(state["turns"])}
            if provider_receipt is not None:
                event["provider_receipt"] = provider_receipt
            state["events"].append(event)
            _cas(review, state, dossier_version=dossier.version)
            return review
    except Exception as exc:
        code = str(exc) if isinstance(exc, ReviewProviderError) else failure_code
        receipt = getattr(exc, "provider_receipt", None)
        if receipt is None:
            receipt = provider_receipt
        with transaction.atomic():
            review = CurriculumTeacherReview.objects.select_for_update().get(job_id=job_id)
            state = copy.deepcopy(review.state)
            event = {"at": timezone.now().isoformat(), "kind": "provider_failure", "code": code,
                     "claim_id": str(token)}
            if receipt is not None:
                event["provider_receipt"] = receipt
            if review.generation_token == token:
                state.update(status="pending", error=code)
                state["events"].append(event)
                _cas(review, state)
            else:
                # A recovered/replaced claim owns the current workflow. Append
                # only this old attempt's audit event; a revision bump would
                # incorrectly invalidate an in-flight successor's result.
                event["kind"] = "provider_result_discarded"
                state["events"].append(event)
                count = CurriculumTeacherReview.objects.filter(
                    pk=review.pk, revision=review.revision, state=review.state,
                    generation_token=review.generation_token).update(
                        state=state, updated_at=timezone.now())
                if count != 1:
                    raise ReviewError("La revisión cambió al registrar el resultado descartado.") from exc
                review.refresh_from_db()
        if isinstance(exc, ReviewError):
            raise
        return review


@_controlled_db_busy
def recover_stale_claim(review, *, expected_revision):
    """Explicit retry only; no automatic repeated provider request after interruption."""
    with transaction.atomic():
        # The caller may predate an audit-only append that deliberately did not
        # invalidate this claim's revision. Recover from the current locked
        # state, preserving those receipts rather than its stale instance.
        review = CurriculumTeacherReview.objects.select_for_update().get(pk=review.pk)
        if review.revision != expected_revision:
            raise ReviewError("La revisión cambió; recarga para continuar.")
        if not review.generation_token or not review.generation_started_at or timezone.now() - review.generation_started_at < CLAIM_TIMEOUT:
            raise ReviewError("La consulta todavía está en curso. La respuesta ya está guardada.")
        state = copy.deepcopy(review.state)
        state.update(status="pending", error="interrupted_request")
        state["events"].append({"at": timezone.now().isoformat(), "kind": "explicit_retry_after_interruption"})
        _cas(review, state)
    return review


@_controlled_db_busy
def resume_changed_dossier(*, job_id, user, expected_revision, expected_version):
    """Explicitly resume after independent edits/reextraction without resetting six turns."""
    with transaction.atomic():
        job = CurriculumImportJob.objects.select_for_update().get(pk=job_id, created_by=user)
        dossier = _ready(job)
        review = CurriculumTeacherReview.objects.select_for_update().get(job=job)
        if review.revision != expected_revision or dossier.version != expected_version or review.generation_token:
            raise ReviewError("La revisión cambió o aún hay una consulta activa. Recarga para continuar.")
        state = copy.deepcopy(review.state)
        state["events"].append({"at": timezone.now().isoformat(), "kind": "explicit_resume_changed_dossier",
                               "previous_version": review.dossier_version, "version": dossier.version,
                               "source_changed": review.source_sha256 != dossier.source_sha256})
        # Never reuse old answer applications as evidence of a different PDF. Their
        # literal history remains, and new output must revalidate existing target IDs.
        if review.source_sha256 != dossier.source_sha256:
            for turn in state["turns"]:
                turn["applied"] = []
        state.update(status="pending", error=state.get("error", "") if state.get("error") in BLOCKING_PROVIDER_ERRORS else "")
        count = CurriculumTeacherReview.objects.filter(pk=review.pk, revision=review.revision).update(
            state=state, revision=review.revision + 1, dossier_version=dossier.version,
            source_sha256=dossier.source_sha256, updated_at=timezone.now())
        if count != 1:
            raise ReviewError("La revisión cambió en otra ventana.")
        review.refresh_from_db()
        return review


@_controlled_db_busy
def save_local_draft(*, job_id, user, expected_revision, expected_epoch, turn_id, text, mode):
    """CAS draft writes cannot resurrect a saved/discarded or newer draft."""
    if mode not in ("answer", "edit", "purpose") or not isinstance(text, str) or len(text) > MAX_ANSWER:
        raise ReviewError("Borrador inválido.", 400)
    review = CurriculumTeacherReview.objects.get(job_id=job_id, job__created_by=user)
    turn = next((t for t in review.state["turns"] if t["id"] == turn_id), None)
    if mode == 'purpose':
        dossier = review.job.get_interpretation_dossier()
        valid_target = (turn_id == PURPOSE_DRAFT_ID and purpose_review_available(review, dossier)
                        and review.source_sha256 == dossier.source_sha256
                        and review.dossier_version == dossier.version)
    else:
        valid_target = bool(turn and (mode == 'answer' and turn['answer'] is None
                                    or mode == 'edit' and turn['answer'] is not None))
    if not valid_target or review.revision != expected_revision or review.draft_epoch != expected_epoch:
        raise ReviewError("La pregunta o el borrador cambió. Este envío no sobrescribirá el más reciente.")
    drafts = local_drafts(review)
    drafts[turn_id] = {"turn_id": turn_id, "text": text, "mode": mode}
    if mode == 'purpose':
        drafts[turn_id].update(source_sha256=dossier.source_sha256, dossier_version=dossier.version)
    count = CurriculumTeacherReview.objects.filter(pk=review.pk, revision=expected_revision,
                                                  draft_epoch=expected_epoch).update(
        draft_state={"drafts": drafts},
        draft_epoch=F("draft_epoch") + 1, updated_at=timezone.now())
    if count != 1:
        raise ReviewError("Otro envío guardó una versión más reciente del borrador.")
    return expected_epoch + 1


@_controlled_db_busy
def discard_local_draft(*, job_id, user, expected_revision, expected_epoch, turn_id):
    review = CurriculumTeacherReview.objects.get(job_id=job_id, job__created_by=user)
    if review.revision != expected_revision or review.draft_epoch != expected_epoch:
        raise ReviewError("El borrador cambió en otra ventana; no se ha descartado.")
    if (not any(turn["id"] == turn_id for turn in review.state["turns"])
            and not (turn_id == PURPOSE_DRAFT_ID and purpose_review_available(review, review.job.get_interpretation_dossier()))):
        raise ReviewError("Pregunta inválida.", 400)
    drafts = local_drafts(review)
    drafts.pop(turn_id, None)
    count = CurriculumTeacherReview.objects.filter(job_id=job_id, job__created_by=user,
        revision=expected_revision, draft_epoch=expected_epoch).update(
            draft_state={"drafts": drafts} if drafts else {},
            draft_epoch=F("draft_epoch") + 1, updated_at=timezone.now())
    if count != 1:
        raise ReviewError("El borrador cambió en otra ventana; no se ha descartado.")
