# Generated by Django 5.2.9 on 2026-08-22 07:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='título')),
                ('objective', models.TextField(blank=True, verbose_name='objetivo')),
                ('micro_lesson', models.TextField(blank=True, verbose_name='microlección')),
                ('questions', wagtail.fields.StreamField([('reactivo', 9)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Enunciado del reactivo', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'label': 'Índice literal de la opción', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto de la opción', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'label': 'Respuesta esperada', 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Retroalimentación de esta opción', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('position', 1), ('text', 2), ('expected', 3), ('feedback', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Opciones ordenadas', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Pista', 'required': False}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Pistas autorizadas', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('prompt', 0), ('options', 6), ('hints', 8)]], {})}, verbose_name='reactivos de opción única')),
                ('final_explanation', models.TextField(blank=True, verbose_name='explicación final autorizada')),
                ('validation_summary', models.TextField(blank=True, editable=False, verbose_name='validación estructural')),
                ('is_demo', models.BooleanField(default=True, editable=False, verbose_name='DemoPackage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CurriculumPackage',
                'verbose_name_plural': 'CurriculumPackages',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
