# Generated by Django 5.2.9 on 2026-08-22 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_editorial_review_workflow'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedpackagesnapshot',
            options={'ordering': ['package_id', 'version']},
        ),
        migrations.AddConstraint(
            model_name='publishedpackagesnapshot',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='unique_package_snapshot_version'),
        ),
    ]
