# Generated by Django 5.2.9 on 2026-08-22 13:24

import importlib

from django.db import migrations, models


def drop_runtime_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module("curriculum.migrations.0009_t06_preparation").drop_guards(
        apps,
        schema_editor,
    )
    importlib.import_module("curriculum.migrations.0010_studentturn").drop_guards(
        apps,
        schema_editor,
    )


def recreate_runtime_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0009_t06_preparation"
    ).recreate_guards(apps, schema_editor)
    importlib.import_module("curriculum.migrations.0010_studentturn").create_guards(
        apps,
        schema_editor,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_t08_pseudonymous_result'),
    ]

    operations = [
        migrations.RunPython(drop_runtime_guards, recreate_runtime_guards),
        migrations.AddField(
            model_name='classroomsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cerrada en'),
        ),
        migrations.AlterField(
            model_name='classroomsession',
            name='status',
            field=models.CharField(choices=[('prepared', 'Preparada'), ('active', 'Activa'), ('stopped', 'Detenida'), ('closed', 'Cerrada')], default='active', max_length=16, verbose_name='estado'),
        ),
        migrations.RunPython(recreate_runtime_guards, drop_runtime_guards),
    ]
