# Generated by Django 5.2.9 on 2026-08-25 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_deviceassignment_claimed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudonymousSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_batch_id', models.UUIDField(db_index=True, verbose_name='lote opaco de resultados')),
                ('snapshot_id', models.PositiveBigIntegerField(verbose_name='id del snapshot')),
                ('snapshot_version', models.PositiveIntegerField(verbose_name='versión del snapshot')),
                ('answers', models.JSONField(default=list, verbose_name='respuestas de la encuesta')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PseudonymousSurveyResponse',
                'verbose_name_plural': 'PseudonymousSurveyResponses',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
