# Generated by Django 5.2.9 on 2026-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_pseudonymoussurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='curriculum_imports/', verbose_name='PDF de la currícula')),
                ('status', models.CharField(choices=[('uploaded', 'PDF cargado'), ('topics_proposed', 'Temas propuestos; en revisión docente'), ('subtopics_proposed', 'Subtemas propuestos; en revisión docente'), ('completed', 'Jerarquía confirmada'), ('failed', 'Procesamiento fallido')], default='uploaded', max_length=24, verbose_name='estado')),
                ('source_text', models.TextField(blank=True, editable=False, verbose_name='texto extraído del PDF')),
                ('page_count', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='páginas detectadas')),
                ('topics', models.JSONField(blank=True, default=list, verbose_name='jerarquía propuesta')),
                ('llm_log', models.JSONField(blank=True, default=list, editable=False, verbose_name='bitácora del modelo local')),
                ('error_message', models.TextField(blank=True, editable=False, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CurriculumImportJob',
                'verbose_name_plural': 'CurriculumImportJobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
