# Generated by Django 5.2.9 on 2026-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_curriculumimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='activities',
            field=models.JSONField(blank=True, default=list, verbose_name='actividades propuestas'),
        ),
        migrations.AddField(
            model_name='curriculumpackage',
            name='ai_assisted',
            field=models.BooleanField(default=False, editable=False, help_text='True si el borrador fue generado con asistencia de IA. No implica validación pedagógica ni autorización de publicación.', verbose_name='borrador asistido por IA'),
        ),
        migrations.AlterField(
            model_name='curriculumimportjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'PDF cargado'), ('topics_proposed', 'Temas propuestos; en revisión docente'), ('subtopics_proposed', 'Subtemas propuestos; en revisión docente'), ('activities_proposed', 'Actividades propuestas; en revisión docente'), ('completed', 'Jerarquía confirmada'), ('converted', 'Borradores generados'), ('failed', 'Procesamiento fallido')], default='uploaded', max_length=24, verbose_name='estado'),
        ),
    ]
