# Generated by Django 5.2.9 on 2026-08-25 21:00

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_curriculumimportjob_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumimportjob',
            name='pdf',
            field=models.FileField(upload_to=curriculum.models.curriculum_import_pdf_path, verbose_name='PDF de la currícula'),
        ),
    ]
