# Generated by Django 5.2.9 on 2026-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_alter_curriculumimportjob_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='progress_done',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='elementos procesados'),
        ),
        migrations.AddField(
            model_name='curriculumimportjob',
            name='progress_stage',
            field=models.CharField(blank=True, editable=False, max_length=24, verbose_name='etapa en curso'),
        ),
        migrations.AddField(
            model_name='curriculumimportjob',
            name='progress_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='inicio de la etapa'),
        ),
        migrations.AddField(
            model_name='curriculumimportjob',
            name='progress_total',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='elementos totales'),
        ),
    ]
