# Generated by Django 5.2.9 on 2026-08-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_curriculumimportjob_progress_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='llm_trace',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='bitácora técnica del modelo local'),
        ),
    ]
