# Generated by Django 5.2.9 on 2026-08-26 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


ROADMAP_UPDATE_TRIGGER = "curriculum_publishedroadmapsnapshot_no_update"
ROADMAP_DELETE_TRIGGER = "curriculum_publishedroadmapsnapshot_no_delete"
SESSION_ROADMAP_TRIGGER = "curriculum_classroomsession_no_roadmap_snapshot_update"


def create_snapshot_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(
        f"""
        CREATE TRIGGER IF NOT EXISTS {ROADMAP_UPDATE_TRIGGER}
        BEFORE UPDATE ON curriculum_publishedroadmapsnapshot
        BEGIN
            SELECT RAISE(ABORT, 'PublishedRoadmapSnapshot is immutable');
        END;
        """
    )
    schema_editor.execute(
        f"""
        CREATE TRIGGER IF NOT EXISTS {ROADMAP_DELETE_TRIGGER}
        BEFORE DELETE ON curriculum_publishedroadmapsnapshot
        BEGIN
            SELECT RAISE(ABORT, 'PublishedRoadmapSnapshot is immutable');
        END;
        """
    )
    schema_editor.execute(
        f"""
        CREATE TRIGGER IF NOT EXISTS {SESSION_ROADMAP_TRIGGER}
        BEFORE UPDATE OF roadmap_snapshot_id ON curriculum_classroomsession
        WHEN OLD.roadmap_snapshot_id IS NOT NEW.roadmap_snapshot_id
        BEGIN
            SELECT RAISE(ABORT, 'ClassroomSession roadmap snapshot is immutable');
        END;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_curriculumimportjob_llm_trace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedRoadmapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='título')),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(verbose_name='roadmap publicado')),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PublishedRoadmapSnapshot',
                'verbose_name_plural': 'PublishedRoadmapSnapshots',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='roadmap_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='curriculum.publishedroadmapsnapshot'),
        ),
        migrations.CreateModel(
            name='CurriculumProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=160, verbose_name='identificador del tema')),
                ('status', models.CharField(choices=[('current', 'Actual'), ('worked', 'Trabajado')], max_length=16, verbose_name='estado confirmado por la maestra')),
                ('confirmed_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_curriculum_progress', to=settings.AUTH_USER_MODEL)),
                ('roadmap_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_progress', to='curriculum.publishedroadmapsnapshot')),
            ],
            options={
                'verbose_name': 'CurriculumProgress',
                'verbose_name_plural': 'CurriculumProgress',
                'ordering': ['node_id'],
                'constraints': [models.UniqueConstraint(fields=('roadmap_snapshot', 'node_id'), name='unique_curriculum_progress_node')],
            },
        ),
        migrations.CreateModel(
            name='StudentRoadmapProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('completed_activity_ids', models.JSONField(blank=True, default=list, verbose_name='actividades completadas en el recorrido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='curriculum.publishedpackagesnapshot')),
                ('roadmap_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='curriculum.publishedroadmapsnapshot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roadmap_progress', to='curriculum.classroomsession')),
                ('turn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to='curriculum.studentturn')),
            ],
            options={
                'verbose_name': 'StudentRoadmapProgress',
                'verbose_name_plural': 'StudentRoadmapProgress',
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'student_key'), name='unique_session_student_roadmap_key')],
            },
        ),
        migrations.RunPython(create_snapshot_guards, migrations.RunPython.noop),
    ]
