# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0023_publishedroadmapsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentroadmapprogress",
            name="correct_question_indices",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="reactivos correctos persistidos por actividad",
            ),
        ),
    ]
