# Generated by Django 5.2.9 on 2026-08-27

import importlib

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def erase_legacy_free_text_surveys(apps, schema_editor):
    """Remove the retired free-text surface before replacing its schema."""

    apps.get_model("curriculum", "PseudonymousSurveyResponse").objects.all().delete()


def backfill_historical_participant_keys(apps, schema_editor):
    """Give every pre-#86 row its own random key during the schema upgrade."""

    for model_name in ("PseudonymousResult", "StudentTurn"):
        model = apps.get_model("curriculum", model_name)
        for row in model.objects.filter(participant_key__isnull=True).iterator():
            model.objects.filter(pk=row.pk).update(participant_key=uuid.uuid4())


def drop_sqlite_guards(apps, schema_editor):
    """Table rebuilds drop SQLite triggers; remove them deliberately first."""

    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).drop_runtime_guards(apps, schema_editor)
    for trigger_name in (
        "curriculum_publishedroadmapsnapshot_no_update",
        "curriculum_publishedroadmapsnapshot_no_delete",
        "curriculum_classroomsession_no_roadmap_snapshot_update",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name};")


def recreate_sqlite_guards(apps, schema_editor):
    """Restore every pre-existing DB boundary after SQLite schema changes."""

    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).create_runtime_guards(apps, schema_editor)
    importlib.import_module(
        "curriculum.migrations.0023_publishedroadmapsnapshot_and_more"
    ).create_snapshot_guards(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0024_studentroadmapprogress_correct_questions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_sqlite_guards, recreate_sqlite_guards),
        migrations.CreateModel(
            name="ClassroomGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nombre del salón")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ClassroomGroup",
                "verbose_name_plural": "ClassroomGroups",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="pseudonymousresult",
            name="activity_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="actividad opaca",
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousresult",
            name="participant_key",
            field=models.UUIDField(
                db_index=True,
                null=True,
                verbose_name="clave seudónima del participante",
            ),
        ),
        migrations.AddField(
            model_name="studentturn",
            name="participant_key",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                null=True,
                verbose_name="clave seudónima del participante",
            ),
        ),
        migrations.RunPython(backfill_historical_participant_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pseudonymousresult",
            name="participant_key",
            field=models.UUIDField(
                db_index=True,
                verbose_name="clave seudónima del participante",
            ),
        ),
        migrations.AlterField(
            model_name="studentturn",
            name="participant_key",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="clave seudónima del participante",
            ),
        ),
        migrations.AddField(
            model_name="classroomgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classroom_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroomsession",
            name="classroom_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="curriculum.classroomgroup",
            ),
        ),
        migrations.RunPython(erase_legacy_free_text_surveys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="pseudonymoussurveyresponse",
            name="answers",
        ),
        migrations.AddField(
            model_name="pseudonymoussurveyresponse",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="calificación de estrellas",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="pseudonymoussurveyresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="survey_rating_between_one_and_five",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomgroup",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name"),
                name="unique_teacher_classroom_group_name",
            ),
        ),
        migrations.RunPython(recreate_sqlite_guards, drop_sqlite_guards),
    ]
