# Generated by Django 5.2.9 on 2026-08-27

import importlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_sqlite_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).drop_runtime_guards(apps, schema_editor)
    for trigger_name in (
        "curriculum_publishedroadmapsnapshot_no_update",
        "curriculum_publishedroadmapsnapshot_no_delete",
        "curriculum_classroomsession_no_roadmap_snapshot_update",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name};")


def recreate_sqlite_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).create_runtime_guards(apps, schema_editor)
    importlib.import_module(
        "curriculum.migrations.0023_publishedroadmapsnapshot_and_more"
    ).create_snapshot_guards(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0025_classroomgroup_and_pseudonymous_retention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_sqlite_guards, recreate_sqlite_guards),
        migrations.AddField(
            model_name="classroomsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classroom_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(recreate_sqlite_guards, drop_sqlite_guards),
    ]
