# Generated by Django 5.2.9 on 2026-08-28 18:33

import importlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_sqlite_guards(apps, schema_editor):
    """Drop guards before SQLite rebuilds ClassroomSession."""

    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).drop_runtime_guards(apps, schema_editor)
    for trigger_name in (
        "curriculum_publishedroadmapsnapshot_no_update",
        "curriculum_publishedroadmapsnapshot_no_delete",
        "curriculum_classroomsession_no_roadmap_snapshot_update",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name};")


def recreate_sqlite_guards(apps, schema_editor):
    """Restore every pre-existing DB boundary after SQLite table rebuilds."""

    if schema_editor.connection.vendor != "sqlite":
        return
    importlib.import_module(
        "curriculum.migrations.0015_t08_closure_receipt_and_constraints"
    ).create_runtime_guards(apps, schema_editor)
    importlib.import_module(
        "curriculum.migrations.0023_publishedroadmapsnapshot_and_more"
    ).create_snapshot_guards(apps, schema_editor)


def mark_legacy_school_scope_unresolved(apps, schema_editor):
    """Mark legacy rows without inventing a School, Director, or assignment."""

    ClassroomGroup = apps.get_model("curriculum", "ClassroomGroup")
    ClassroomSession = apps.get_model("curriculum", "ClassroomSession")
    ClassroomGroup.objects.filter(school__isnull=True).update(
        legacy_school_unresolved=True
    )
    ClassroomSession.objects.filter(school__isnull=True).update(
        legacy_school_unresolved=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_curriculumimportjob_progress_finished_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_sqlite_guards, recreate_sqlite_guards),
        migrations.CreateModel(
            name='InstitutionalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_display_name', models.CharField(max_length=160, verbose_name='nombre histórico de presentación')),
                ('actor_role', models.CharField(blank=True, max_length=80, verbose_name='función histórica')),
                ('action', models.CharField(max_length=80, verbose_name='acción')),
                ('object_type', models.CharField(max_length=80, verbose_name='tipo de objeto')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='referencia interna del objeto')),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='manual', max_length=80, verbose_name='origen')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'InstitutionalAuditEvent',
                'verbose_name_plural': 'InstitutionalAuditEvents',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre de la School')),
                ('modality', models.CharField(choices=[('primary', 'Primaria'), ('secondary_general', 'Secundaria general'), ('secondary_technical', 'Secundaria técnica'), ('telesecundaria', 'Telesecundaria')], default='primary', max_length=32, verbose_name='modalidad pedagógica')),
                ('is_configured', models.BooleanField(default=True, verbose_name='School configurada')),
                ('archived', models.BooleanField(default=False, verbose_name='archivada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, default='', max_length=120, verbose_name='función')),
                ('subject', models.CharField(blank=True, default='', max_length=120, verbose_name='materia')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('ended', 'Terminada'), ('rejected', 'Rechazada'), ('archived', 'Archivada')], default='active', max_length=16, verbose_name='estado')),
                ('source', models.CharField(default='manual', max_length=80, verbose_name='origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='terminada en')),
            ],
            options={
                'verbose_name': 'TeacherAssignment',
                'verbose_name_plural': 'TeacherAssignments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='classroomgroup',
            name='unique_teacher_classroom_group_name',
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ciclo escolar'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archivado'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archivado en'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_directed_classroom_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='grado'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='clave de grupo'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='legacy_school_unresolved',
            field=models.BooleanField(default=False, editable=False, verbose_name='School histórica no recuperable'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='modality',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='modalidad'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='turno'),
        ),
        migrations.AlterField(
            model_name='classroomsession',
            name='classroom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='curriculum.classroomgroup'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='legacy_school_unresolved',
            field=models.BooleanField(default=False, editable=False, verbose_name='School histórica no recuperable'),
        ),
        migrations.AddField(
            model_name='institutionalauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutional_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionalauditevent',
            name='classroom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='curriculum.classroomgroup'),
        ),
        migrations.AddField(
            model_name='school',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionalauditevent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='curriculum.school'),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_groups', to='curriculum.school'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='curriculum.school'),
        ),
        migrations.RunPython(
            mark_legacy_school_scope_unresolved,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='classroomgroup',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'modality', 'grade', 'group_key', 'shift'), name='unique_school_classroom_identity'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='classroom_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='curriculum.classroomgroup'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='curriculum.school'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(recreate_sqlite_guards, drop_sqlite_guards),
    ]
