# Generated by Django 5.2.9 on 2026-09-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_curriculumimportjob_cancel_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('resources', 'Recursos'), ('session_operation', 'Operación de sesión'), ('family_communication', 'Comunicación general con familias'), ('technical_training', 'Apoyo técnico o capacitación')], max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En atención'), ('needs_clarification', 'Requiere aclaración'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to='curriculum.classroomgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to='curriculum.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
