# Generated by Django 5.2.9 on 2026-09-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_support_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumpackage',
            name='source_references',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Páginas y recursos de origen conservados para revisión y snapshots; no son reescritos por la asistencia automática.', verbose_name='referencias de fuente'),
        ),
    ]
