# Generated by Django 5.2.9 on 2026-09-01 21:30

import curriculum.models
from django.db import migrations, models


def recreate_snapshot_immutability_triggers(apps, schema_editor):
    """SQLite table rebuilds can drop triggers while adding snapshot fields."""

    if schema_editor.connection.vendor != "sqlite":
        return
    schema_editor.execute(
        """
        CREATE TRIGGER IF NOT EXISTS curriculum_publishedpackagesnapshot_no_update
        BEFORE UPDATE ON curriculum_publishedpackagesnapshot
        BEGIN
            SELECT RAISE(ABORT, 'PublishedPackageSnapshot is immutable');
        END;
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER IF NOT EXISTS curriculum_publishedpackagesnapshot_no_delete
        BEFORE DELETE ON curriculum_publishedpackagesnapshot
        BEGIN
            SELECT RAISE(ABORT, 'PublishedPackageSnapshot is immutable');
        END;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_preserve_source_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumpackage',
            name='source_pdf',
            field=models.FileField(blank=True, editable=False, help_text='Copia inmutable de la fuente usada para este borrador; no se expone sin autorización.', null=True, upload_to=curriculum.models._package_source_upload_to, verbose_name='PDF fuente conservado'),
        ),
        migrations.AddField(
            model_name='curriculumpackage',
            name='source_pdf_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 del PDF fuente'),
        ),
        migrations.AddField(
            model_name='publishedpackagesnapshot',
            name='source_pdf',
            field=models.FileField(blank=True, editable=False, help_text='Copia inmutable de la fuente conservada para auditoría autorizada.', null=True, upload_to=curriculum.models._published_source_upload_to, verbose_name='PDF fuente publicado'),
        ),
        migrations.AddField(
            model_name='publishedpackagesnapshot',
            name='source_pdf_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 del PDF publicado'),
        ),
        migrations.RunPython(recreate_snapshot_immutability_triggers, migrations.RunPython.noop),
    ]
