# Generated by Django 5.2.9 on 2026-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_curriculumpackage_source_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='interpretation_dossier',
            field=models.JSONField(blank=True, default=dict, help_text='Dossier estructurado y versionado de interpretación curricular V0.', verbose_name='dossier de interpretación V0'),
        ),
    ]
