# Generated by Django 5.2.9 on 2026-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_curriculumimportjob_interpretation_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='interpretation_claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='token de reclamo de interpretación'),
        ),
        migrations.AddField(
            model_name='curriculumimportjob',
            name='interpretation_claimed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de reclamo de interpretación'),
        ),
    ]
