# Generated by Django 5.2.9 on 2026-09-12 14:36

from django.db import migrations, models


import hashlib
import re

HEX_64_REGEX = re.compile(r"^[0-9a-fA-F]{64}$")


def migrate_interpretation_states(apps, schema_editor):
    CurriculumImportJob = apps.get_model('curriculum', 'CurriculumImportJob')

    for job in CurriculumImportJob.objects.all():
        raw_dossier = job.interpretation_dossier
        target_state = 'not_started'
        is_ready = False

        if isinstance(raw_dossier, dict) and raw_dossier:
            version = raw_dossier.get('version')
            dossier_status = raw_dossier.get('status')
            source_sha = raw_dossier.get('source_sha256')

            if (
                isinstance(version, int)
                and not isinstance(version, bool)
                and version >= 1
                and dossier_status == 'active'
                and isinstance(source_sha, str)
                and bool(HEX_64_REGEX.match(source_sha.strip()))
                and bool(job.pdf and getattr(job.pdf, 'name', None))
            ):
                try:
                    storage = getattr(job.pdf, 'storage', None)
                    name = job.pdf.name
                    if storage and storage.exists(name):
                        with storage.open(name, 'rb') as stream:
                            content = stream.read()
                        file_sha = hashlib.sha256(content).hexdigest()
                        if file_sha.lower() == source_sha.strip().lower():
                            is_ready = True
                except Exception:
                    is_ready = False

        if job.interpretation_claim_token:
            target_state = 'organizing'
        elif is_ready:
            target_state = 'ready'
        else:
            target_state = 'not_started'

        if job.interpretation_state != target_state:
            job.interpretation_state = target_state
            job.save(update_fields=['interpretation_state'])


def reverse_interpretation_states(apps, schema_editor):
    CurriculumImportJob = apps.get_model('curriculum', 'CurriculumImportJob')
    CurriculumImportJob.objects.all().update(interpretation_state='not_started')


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0036_curriculumimportjob_interpretation_claim_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='interpretation_state',
            field=models.CharField(choices=[('not_started', 'No iniciada'), ('organizing', 'Organizando planeación'), ('ready', 'Planeación organizada/lista para revisar'), ('failed', 'Interpretación interrumpida o fallida')], db_index=True, default='not_started', help_text="Estado canónico del ciclo de vida de interpretación V0 de la fuente (not_started, organizing, ready, failed). Es ortogonal e independiente del campo 'status' del pipeline legado de temas/subtemas.", max_length=24, verbose_name='estado de interpretación'),
        ),
        migrations.AlterField(
            model_name='curriculumimportjob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'PDF cargado'), ('topics_proposed', 'Temas propuestos; en revisión docente'), ('subtopics_proposed', 'Subtemas propuestos; en revisión docente'), ('activities_proposed', 'Actividades propuestas; en revisión docente'), ('completed', 'Jerarquía confirmada'), ('converted', 'Borradores generados'), ('failed', 'Procesamiento fallido')], default='uploaded', help_text="Estado del pipeline legado de extracción jerárquica y autoría (temas, subtemas, actividades y conversión). STATUS_UPLOADED indica únicamente que el PDF fuente fue recibido y aceptado en storage; el ciclo de interpretación de la fuente es gobernado por 'interpretation_state'.", max_length=24, verbose_name='estado'),
        ),
        migrations.RunPython(
            migrate_interpretation_states,
            reverse_code=reverse_interpretation_states,
        ),
    ]
