# Generated by Django 5.2.9 on 2026-09-12 22:15

from django.db import migrations, models


def copy_interpretation_errors(apps, schema_editor):
    CurriculumImportJob = apps.get_model('curriculum', 'CurriculumImportJob')
    for job in CurriculumImportJob.objects.filter(interpretation_state='failed'):
        if job.error_message:
            job.interpretation_error_message = job.error_message
            job.save(update_fields=['interpretation_error_message'])


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0037_curriculumimportjob_interpretation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumimportjob',
            name='interpretation_error_message',
            field=models.TextField(
                blank=True,
                default='',
                help_text="Mensaje de error específico del ciclo de vida de interpretación V0. Es ortogonal e independiente del campo 'error_message' del pipeline legado.",
                verbose_name='error de interpretación',
            ),
        ),
        migrations.RunPython(
            copy_interpretation_errors,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
