# Generated by Django 5.2.9 on 2026-09-13 23:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0038_curriculumimportjob_interpretation_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumImportApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_version', models.PositiveIntegerField(verbose_name='versión del dossier')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='SHA-256 del PDF fuente')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de aprobación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aprobación vigente')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de invalidación')),
                ('invalidation_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='motivo de invalidación')),
                ('pending_items_count', models.PositiveIntegerField(default=0, verbose_name='elementos opcionales pendientes')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_import_approvals', to=settings.AUTH_USER_MODEL, verbose_name='docente que aprobó')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='curriculum.curriculumimportjob', verbose_name='trabajo de importación')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_approvals', to='curriculum.curriculumpackage', verbose_name='paquete curricular borrador')),
            ],
            options={
                'verbose_name': 'CurriculumImportApproval',
                'verbose_name_plural': 'CurriculumImportApprovals',
                'ordering': ['-approved_at', '-id'],
            },
        ),
    ]
