# Generated by Django for Task 7 B1-B6 correction

import django.db.models.deletion
from django.db import migrations, models


def populate_existing_approvals(apps, schema_editor):
    Approval = apps.get_model("curriculum", "CurriculumImportApproval")
    for approval in Approval.objects.all():
        updated = False
        if not approval.dossier_snapshot and approval.job_id:
            job = approval.job
            if job and getattr(job, "interpretation_dossier", None):
                dossier = job.interpretation_dossier
                if isinstance(dossier, dict) and dossier.get("version") == approval.dossier_version:
                    approval.dossier_snapshot = dossier
                    updated = True
        if approval.pending_items_count > 0 and not approval.pending_acknowledged:
            approval.pending_acknowledged = True
            updated = True
        if updated:
            approval.save(update_fields=["dossier_snapshot", "pending_acknowledged"])


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0039_curriculumimportapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumimportapproval",
            name="dossier_snapshot",
            field=models.JSONField(default=dict, verbose_name="snapshot canónico del dossier"),
        ),
        migrations.AddField(
            model_name="curriculumimportapproval",
            name="pending_acknowledged",
            field=models.BooleanField(default=False, verbose_name="elementos pendientes reconocidos"),
        ),
        migrations.AlterField(
            model_name="curriculumimportapproval",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_approvals",
                to="curriculum.curriculumpackage",
                verbose_name="paquete curricular borrador",
            ),
        ),
        migrations.RenameField(
            model_name="curriculumimportapproval",
            old_name="is_active",
            new_name="_is_active",
        ),
        migrations.AlterField(
            model_name="curriculumimportapproval",
            name="_is_active",
            field=models.BooleanField(
                db_column="is_active",
                default=True,
                editable=False,
                verbose_name="aprobación vigente",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumimportapproval",
            name="invalidated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="fecha de invalidación",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumimportapproval",
            name="invalidation_reason",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
                verbose_name="motivo de invalidación",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumimportapproval",
            constraint=models.UniqueConstraint(
                fields=("job", "dossier_version"),
                name="unique_curriculum_import_approval_job_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumimportapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("dossier_version__gt", 0)),
                name="check_approval_dossier_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumimportapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_items_count__gte", 0)),
                name="check_approval_pending_items_count_gte_zero",
            ),
        ),
        migrations.RunPython(
            populate_existing_approvals,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
