# Generated by Django 5.2.9 on 2026-09-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_curriculumimportapproval_append_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumimportapproval',
            name='_is_active',
        ),
    ]
