# Generated by Django 5.2.9 on 2026-09-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0041_remove_curriculumimportapproval_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSourceBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='SHA-256')),
                ('content', models.BinaryField(verbose_name='contenido binario')),
                ('content_size', models.PositiveBigIntegerField(editable=False, verbose_name='tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'CurriculumSourceBlob',
                'verbose_name_plural': 'CurriculumSourceBlobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='curriculumimportapproval',
            name='source_blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='curriculum.curriculumsourceblob', verbose_name='blob fuente inmutable'),
        ),
        migrations.AddField(
            model_name='curriculumpackage',
            name='source_blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='curriculum.curriculumsourceblob', verbose_name='blob fuente inmutable'),
        ),
    ]
