# Generated by Django 5.2.9 on 2026-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0042_curriculumsourceblob_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumsourceblob',
            constraint=models.CheckConstraint(condition=models.Q(('content_size__gt', 0)), name='check_curriculum_source_blob_content_size_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsourceblob',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='check_curriculum_source_blob_sha256_format'),
        ),
    ]
